apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: todo
  namespace: argocd

spec:
  generators:
  - list:
      elements:
      - env: dev
      - env: qa
      - env: prod
  template:
    metadata:
      labels:
        app_env: '{{env}}'
      name: todo-{{env}}
    spec:
      destination:
        namespace: todo-{{env}}
        server: https://host.docker.internal:26443
      project: todo
      source:
        helm:
          parameters:
          - name: git.commit
            value: '{{revision}}'
          valueFiles:
          - environments/{{env}}/values.yaml
        path: charts/
        repoURL: https://github.com/mturnaviotov/go-k8s-test-app.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
