apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: todo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Todo

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - "*"
  # дозволені місця деплою; можна звузити до певних namespace/серверів
  destinations:
  - namespace: "*"
    server: "*"
  # додаткові флаги (опціонально)
namespaceResourceWhitelist:
- group: '*'
  kind: '*'
clusterResourceWhitelist:
- group: '*'
  kind: '*'
