apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: todo
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=zero"]
  generators:
    - merge:
        mergeKey: env
        generators:
          - list:
              elements:
                - env: dev
                - env: prod
          - git:
              repoURL: https://github.com/mturnaviotov/k8s-argo.git
              revision: main
              files:
                - path: "environments/{{env}}/values.yaml"
  template:
    metadata:
      name: "todo-{{.env}}"
      labels:
        app.kubernetes.io/part-of: todo-project
        # При goTemplate: true звернення до змінних йде через крапку
        tag: '{{index . "backend" "image" "tag"}}'
    spec:
      project: todo
      sources:
        # Основний чарт
        - repoURL: https://github.com/mturnaviotov/k8s-test-app.git
          targetRevision: main
          path: charts/
          helm:
            valueFiles:
              - $values/environments/{{.env}}/values.yaml
        # Репозиторій з конфігураціями (для $values)
        - repoURL: https://github.com/mturnaviotov/k8s-argo.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc # Або ваш кастомний хост
        namespace: "todo-{{.env}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true