apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: todo
    app.kubernetes.io/image: "{{backend.image.tag}}"
spec:
  project: todo
  source:
    repoURL: https://github.com/mturnaviotov/k8s-test-app.git
    targetRevision: HEAD
    path: charts/
  destination:
    server: https://host.docker.internal:26443
    namespace: todo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
