apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: todo
  namespace: argocd

spec:
  goTemplate: true
  GoTemplateOptions:
    missingkey: zero
  generators:
    merge:
      mergeKey: env
      generators:
        - list:
            elements:
              - env: dev
              - env: prod
        - git:
            repoURL:
              repoURL: https://github.com/mturnaviotov/k8s-argo.git
              revision: main
              files:
                - path: environments/{{env}}/values.yaml
  template:
    metadata:
      name: todo-{{env}}
      labels:
        app.kubernetes.io/part-of: todo-project
        tag: "{{.backend.image.tag}}"
    spec:
      destination:
        namespace: todo-{{env}}
        server: https://host.docker.internal:26443
      project: todo
      sources:
        - helm:
            valueFiles:
              - $values/environments/{{env}}/values.yaml
          path: charts/
          repoURL: https://github.com/mturnaviotov/k8s-test-app.git
          targetRevision: main
        - directory: {}
          path: .
          ref: values
          repoURL: https://github.com/mturnaviotov/k8s-argo.git
          targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
